### ISSUE TITLE
Problem hosting on Apache

### ISSUE THREAD

**Issue by wuppo** [richwalm/nzaarttrainer#2]
Owing to the wsgi required to serve python/Flask under Apache, the questions database is not found.  Code change below fixes that.

Origional:-

**InputFile = open('questions.json')
Data = json.load(InputFile)
InputFile.close()**

Updated to:-

**with app.open_resource('questions.json') as InputFile:
    Data = json.load(InputFile)
InputFile.close()**

**Comment by richwalm** [comment]
Thank you. I've included this change.

**Comment by wuppo** [comment]
Cheers Richard,
Nice app! I had one person gain his licence as a direct result of using it - he had been 'studying' for a couple it years before..
Regds
Dave Larcombe
